const CountryNames = [
  { name: 'Algeria', source: 'square/algeria.webp' },
  { name: 'Bahrain', source: 'square/bahrain.webp' },
  { name: 'Comoros', source: 'square/comoros.webp' },
  { name: 'Djibouti', source: 'square/djibouti.webp' },
  { name: 'Egypt', source: 'square/egypt.webp' },
  { name: 'Iraq', source: 'square/iraq.webp' },
  { name: 'Jordan', source: 'square/jordan.webp' },
  { name: 'Kuwait', source: 'square/kuwait.webp' },
  { name: 'Lebanon', source: 'square/lebanon.webp' },
  { name: 'Libya', source: 'square/libya.webp' },
  { name: 'Mauritania', source: 'square/mauritania.webp' },
  { name: 'Morocco', source: 'square/morocco.webp' },
  { name: 'Oman', source: 'square/oman.webp' },
  { name: 'Palestine', source: 'square/palestine.webp' },
  { name: 'Qatar', source: 'square/qatar.webp' },
  { name: 'Saudi Arabia', source: 'square/saudiarabia.webp' },
  { name: 'Somalia', source: 'square/somalia.webp' },
  { name: 'Sudan', source: 'square/sudan.webp' },
  { name: 'Syria', source: 'square/syria.webp' },
  { name: 'Tunisia', source: 'square/tunisia.webp' },
  { name: 'Use', source: 'square/usa.webp' },
  { name: 'Yemen', source: 'square/yemen.webp' },
  { name: 'Iran', source: 'square/iran.webp' },
  { name: 'Turkey', source: 'square/turkey.webp' },
  { name: 'USA', source: 'square/usa.webp' },
  { name: 'Russia', source: 'square/russia.webp' },
  { name: 'China', source: 'square/china.webp' },
];

export { CountryNames };
