const CountryNames = [
  { name: 'Algeria', source: 'square/algeria.png' },
  { name: 'Bahrain', source: 'square/bahrain.png' },
  { name: 'Comoros', source: 'square/comoros.png' },
  { name: 'Djibouti', source: 'square/djibouti.png' },
  { name: 'Egypt', source: 'square/egypt.png' },
  { name: 'Iraq', source: 'square/iraq.png' },
  { name: 'Jordan', source: 'square/jordan.png' },
  { name: 'Kuwait', source: 'square/kuwait.png' },
  { name: 'Lebanon', source: 'square/lebanon.png' },
  { name: 'Libya', source: 'square/libya.png' },
  { name: 'Mauritania', source: 'square/mauritania.png' },
  { name: 'Morocco', source: 'square/morocco.png' },
  { name: 'Oman', source: 'square/oman.png' },
  { name: 'Palestine', source: 'square/palestine.png' },
  { name: 'Qatar', source: 'square/qatar.png' },
  { name: 'Saudi Arabia', source: 'square/saudi arabia.png' },
  { name: 'Somalia', source: 'square/somalia.png' },
  { name: 'Sudan', source: 'square/sudan.png' },
  { name: 'Syria', source: 'square/syria.png' },
  { name: 'Tunisia', source: 'square/tunisia.png' },
  { name: 'Use', source: 'square/usa.png' },
  { name: 'Yemen', source: 'square/yemen.png' },
  { name: 'Iran', source: 'square/iran.png' },
  { name: 'Turkey', source: 'square/turkey.png' },
  { name: 'USA', source: 'square/usa.png' },
  { name: 'Russia', source: 'square/russia.png' },
  { name: 'China', source: 'square/china.png' },
];

export { CountryNames };
